### ISSUE TITLE
Blocage du chargement du contenu mixte actif 

### ISSUE THREAD

**Issue by yaf** [la-contree/baseline#1]
![screen-shot-baseline-mixedcontent](https://user-images.githubusercontent.com/42057/33072722-dc95a72c-cec0-11e7-8003-beeed07f01fc.png)

J'ai comme qui dirait un petit soucis d'affichage.

Blocage du chargement du contenu mixte actif (mixed active content) « http://api.daktary.com/la-contree/baseline/tree/master/events »

Avec un lien vers : https://developer.mozilla.org/fr/docs/S%C3%A9curit%C3%A9/MixedContent

Je me sent un peu sec, et je vais apprendre beaucoup de ce soucis je pense. En attendant; je pose tout ça ici.

Je suis sur un firefox 53.0.3 (32 bits) sur un windows 7 pro sur un réseau pro (filaire, Enedis) avec un firewall un peu sévère.

**Comment by avernois** [comment]
Mixed content, souvent, ça veut dire que l'on cherche à charger du contenu provenant d'une source non sécurisée (http) depuis une page sécurisé (https). Et ça, les navigateurs le bloque (la plupart).

Ca semble le cas ici : la page chargée https://la-contree.github.io/baseline mais le fetch est http://api.daktary.com/... 

J'ai l'impression que github.io fait maintenant directement une redirection vers du https lorsque l'on fait une requête http et ne sert plus rien en http.

Une solution serait de mettre un certificat ssl sur api.daktary.com et de faire le fetch en https. (note: sur une instance heroku hobby, ça se fait en qq clics).

note bis: si github.io fait la redirection systématique en https comme j'ai l'impression, plus aucun site hébergé sur github.io utilisant un fetch vers http://api.daktary.com ne devrait fonctionner.

**Comment by pointbar** [comment]
On se lance avec @avernois pour passer de heroku free vers heroku hobby. Go!

**Comment by pointbar** [comment]
@yaf - on a pris l'hébergement et demandé un certifcat ssl.
En faisant passer la requète fetch de baseline de http à https - ça semble résoudre le pépin.
> #2

**Comment by yaf** [comment]
Merci bien, c'est cool, ça fonctionne.
